import struct
import pywt
import os

def float_to_ieee754_hex(f):
    """将 Python float 转换为 IEEE 754 32位十六进制字符串"""
    # 使用 struct 将 float 打包为 4 字节，再解包为无符号整数
    packed = struct.pack('>f', f)
    ieee754_int = struct.unpack('>I', packed)[0]
    # 返回 8 位十六进制字符串（例如：3f800000）
    return f"{ieee754_int:08x}"

def generate_verilog_coeffs_fp32(file_path="./coef_params_fp32.vh"):
    """
    生成 sym4 小波系数并写入为 FP32 格式的 Verilog 参数文件
    """
    # 1. 获取 sym4 系数
    wavelet = pywt.Wavelet('sym4')
    h_dec_float = wavelet.dec_lo  # 分解低通
    g_dec_float = wavelet.dec_hi  # 分解高通 (如果你也需要高通的话)
    
    # 确保输出目录存在
    output_dir = os.path.dirname(file_path)
    if output_dir and not os.path.exists(output_dir):
        os.makedirs(output_dir)

    print(f"Generating FP32 Verilog parameters for sym4...")

    with open(file_path, 'w') as f:
        f.write(f"// Auto-generated by Python script for FP32\n")
        f.write(f"// Format: IEEE 754 Single Precision (32-bit)\n\n")

        # -------------------------------------------------
        # 写入分解低通系数 (DEC_LO)
        # -------------------------------------------------
        f.write("// Decomposition Low-pass Coefficients (FP32)\n")
        for i, val in enumerate(h_dec_float):
            hex_val = float_to_ieee754_hex(val)
            # 在 Verilog 中，FP32 通常定义为 32'h...
            line = f"parameter DEC_H{i} = 32'h{hex_val}; // Float: {val:.8f}\n"
            f.write(line)

        f.write("\n")

        # -------------------------------------------------
        # # 写入分解高通系数 (DEC_HI)
        # # -------------------------------------------------
        # f.write("// Decomposition High-pass Coefficients (FP32)\n")
        # for i, val in enumerate(g_dec_float):
        #     hex_val = float_to_ieee754_hex(val)
        #     line = f"parameter DEC_HI_{i} = 32'h{hex_val}; // Float: {val:.8f}\n"
        #     f.write(line)

        # -------------------------------------------------
        # 写入重构系数 (逆序逻辑示例)
        # -------------------------------------------------
        f.write("\n// Reconstruction Logic (Reference to DEC)\n")
        for i in range(len(h_dec_float)):
            target_idx = len(h_dec_float) - 1 - i
            line = f"parameter REC_H{i} = DEC_H{target_idx};\n"
            f.write(line)

    print(f"-> Successfully written to {file_path}")

if __name__ == "__main__":
    # 建议在新设备上运行前，确认这个路径是否正确
    # 你可以根据实际路径修改，或者直接使用 "./coef_params_fp32.vh"
    target_path = "E:/project/pulse-processing/verilog_wavelet/fp32_prj/project_1/wavelet_sym4_dec_res_verilog_fp32/scr/coef_params.vh"
    generate_verilog_coeffs_fp32(file_path=target_path)